.base:
  # See https://gitlab.com/gitlab-org/cluster-integration/cluster-applications/
  variables:
    DOCKER_AUTH_CONFIG: ${HOME_NEXUS_DOCKER_AUTH_CONFIG}
  # image: "$HOME_NEXUS_DOCKER_REGISTRY_PROXY/ymdllc/containers/podman-dind:latest"
  timeout: 3h 30m

.clone_ansible_resources:
  variables: &clone_ansible_resources_variables
    ANSIBLE_HOST_KEY_CHECKING: "false"
    ANSIBLE_TIMEOUT: 30
    INVENTORY_REPO: https://github.com/JamesJonesConsulting/AnsibleInventory.git
    INVENTORY_BRANCH: main
    VAULT_REPO: https://github.com/JamesJonesConsulting/AnsibleVault.git
    VAULT_BRANCH: main
  prereq_script: &prereq_deps
    - dnf install -y git ansible* podman-docker
  before_script: &clone_ansible_resources_before_script
    - cp "$PRIVATE_CLONE_NETRC" ~/.netrc; chmod 0600 ~/.netrc
    - git clone -b $INVENTORY_BRANCH --single-branch $INVENTORY_REPO inventory
    - git clone -b $VAULT_BRANCH --single-branch $VAULT_REPO vault
  script: &clone_ansible_resources_script
    - eval $(ssh-agent); ssh-add <(echo "$HOME_SSH_PRIVATE_KEY" | base64 -d);
    - echo -n "$HOME_ANSIBLE_VAULT_KEY" > .vault
    - ansible-galaxy collection install -r ansible/requirements.yml

image: quay.io/podman/stable:latest
stages:
  - provision
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
variables:
  INVENTORY_ENV:
    value: home
    options:
      - home
    description: Inventory environment name
  TAG_VERSION:
    value: latest
    description: Nexus Tag Version
  OPENLDAP_TAG_VERSION:
    value: latest
    description: OpenLDAP Tag Version

maintain_vip:
  stage: provision
  extends: .base
  tags:
    - build
    - medium
  # environment:
  #   name: production
  #   action: prepare
  variables:
    <<: *clone_ansible_resources_variables
    # ANSIBLE_VAULT_VARIABLES_FILE: vault/home/vip_router/vip_router.yml
    # ANSIBLE_VAULT_VARIABLES_CONSUL_FILE: vault/home/consul/consul.yml
  rules:
    - if: $INVENTORY_ENV == "home"
      variables:
        MACHINE_GROUP: "nexus"
        HOST_NAME: nexus.jamesjonesconsulting.com
        LDAP_ROOT: $HOME_LDAP_ROOT
        LDAP_USER: $HOME_LDAP_USER
        LDAP_PASSWORD: $HOME_LDAP_PASSWORD
        LDAP_ADMIN_USER: $HOME_LDAP_ADMIN_USER
        LDAP_ADMIN_PASSWORD: $HOME_LDAP_ADMIN_PASSWORD
  before_script:
    - *prereq_deps
    - *clone_ansible_resources_before_script
  script:
    - *clone_ansible_resources_script
    - ls -all
    - >-
        ansible-playbook -i inventory/$INVENTORY_ENV/hosts 
        --vault-password-file .vault
        ansible/playbook.yml 
        -e "inventory_group_name=$MACHINE_GROUP"
        -e "inventory=$INVENTORY_ENV" -vvv

    # - echo "$HOME_COMPOSER_ADMIN" > admin.json; cat admin.json
