parameters:
  - name: network
    type: string
    default: sgan
  - name: vault
    type: string
  - name: networks
    type: object
    default:
      ymd:
        group: nexus
        agent_key: ymd_agent_key
      sgan:
        group: nexus
        agent_key: sgan_agent_key

steps:
  - checkout: self
  - task: DownloadSecureFile@1
    name: agentKey # The name with which to reference the secure file's path on the agent, like $(mySecureFile.secureFilePath)
    inputs:
      secureFile: ${{ parameters.networks[parameters.network]['agent_key'] }}
  - bash: |
      eval $(ssh-agent -s); cat $(agentKey.secureFilePath) | ssh-add -; echo "${{ parameters.vault }}" > $(Agent.TempDirectory)/.keyvault
      ansible-galaxy install -r ansible/requirements.yml -p ansible/roles
      # ansible-playbook --vault-password-file=$(Agent.TempDirectory)/.keyvault -i ansible/roles/inventory/${{ parameters.network }} ansible/playbook.yml -e 'inventory_group_name=${{ parameters.networks[parameters.network].group }}' -vvv
    # workingDirectory: $(Build.Repository.Name)
    displayName: Connect to Nexus hosts and setup pre-requirements
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
