parameters:
  - name: deploy_net
    displayName: Deployment target network
    default: onprem
    values:
      - onprem
      - onprem-atl
      - staging
      - perf
      - perfax09
      - cl3
  - name: deploy_env
    displayName: Deployment Environment
    type: string
    default: PD
    values:
      - PD
      - NONPRD
  - name: deploy_group
    displayName: Deployment Inventory Group
    type: string
    default: nexus_new
    values:
      - nexus
      - nexus_atl
      - nexus_patch
  - name: nexus_ver
    displayName: Nexus Version
    type: string
    default: '3.38.1-ubi-1'
    values:
      - '3.38.1-ubi-1'
      - '3.37.3-ubi-1'
      - '3.30.1'
      - '3.29.2'
      - '3.28.0'
      - '3.26.1'
      - '3.25.1'
      - '3.24.0'

resources:
  repositories:
  - repository: certs
    type: git
    name: devops_certs    
  - repository: network_bootstrap
    type: git
    name: devops_network-pipeline-templates
    ref: refs/heads/master # optional ref to pin to
    # ref: refs/tags/v1.0 # optional ref to pin to
  containers:
  - container: vmware
    image: nexus01.pd.pods.com:5443/pods-llc/swe/containers/base/devops_ansible_vmware_container:latest
    endpoint: pods_nexus_registry
trigger: none
variables:
  - template: .network_vars.yml@network_bootstrap
    parameters:
      deploy_net: ${{ parameters['deploy_net'] }}
      deploy_group: ${{ parameters.deploy_group }}
      deploy_env: ${{ parameters.deploy_env }}
stages:
  - stage: DeployNexus
    displayName: Deploy Nexus
    variables:
      - name: NEXUS_VER
        value: ${{ parameters['nexus_ver'] }}
      - template: .connect_vars.yml@network_bootstrap
        parameters:
          deploy_net: ${{ parameters['deploy_net'] }}
    jobs:
      - deployment: NexusHostPrep
        displayName: Preparing Nexus Host
        environment: "nexus"
        pool: $(DEPLOY_POOL)
        # container: vmware
        strategy:
          runOnce:
            deploy:
              steps:
                - template: .pre.yml
      - template: .deploy.yml
        parameters:
          deploy_version: ${{ parameters.nexus_ver }}
          ${{ if eq(parameters.deploy_group,'nexus_atl') }}:
            tags: "onprem-atl,${{ parameters.deploy_env }}"
          ${{ else }}:
            tags: "${{ parameters.deploy_net }},${{ parameters.deploy_env }}"
      - job: NexusHostPost
        displayName: Setup boot persistance for Nexus containers
        dependsOn:
          - NexusDeployment
        condition: succeeded()
        pool: $(DEPLOY_POOL)
        # ${{ if eq(parameters['deploy_net'],'onprem') }}:
        #   container: win_rm
        steps:
          - template: .post.yml


