parameters:
  - name: network
    displayName: Deployment target network
    default: sgan
    values:
      - sgan
      - ymd
  - name: nexus_version
    displayName: Nexus Version
    type: string
    default: latest
  - name: openldap_version
    displayName: Nexus Version
    type: string
    default: latest
trigger: none
variables:
  - group: ansible
  - group: openldap

extends: 
  template: .podman.yml
  parameters:
    network: ${{ parameters.network }}
    version: 
      openldap: ${{ parameters.openldap_version }}
      nexus3: ${{ parameters.nexus_version }}
    ${{ if in(parameters.network,'sgan')}}:
      vault: $(YMD_ANSIBLE_VAULT_KEY)
      ldap:
        root: $(SGAN_LDAP_ROOT)
        user: $(SGAN_USER)
        password: $(SGAN_PASSWORD)
        admin:
          user: $(SGAN_ADMIN_USER)
          password: $(SGAN_ADMIN_PASSWORD)
    ${{ if in(parameters.network,'ymd')}}:
      vault: $(YMD_ANSIBLE_VAULT_KEY)
      ldap:
        root: $(YMD_LDAP_ROOT)
        user: $(YMD_USER)
        password: $(YMD_PASSWORD)
        admin:
          user: $(YMD_ADMIN_USER)
          password: $(YMD_ADMIN_PASSWORD)

# variables:
#   - group: ansible
# stages:
#   - stage: PrePrepNexus
#     displayName: Setup Nexus Pre-Prep Host Requirements
#     jobs:
#       - template: .pre.yml
#         parameters:
#           network: ${{ parameters.network }}
#           version: ${{ parameters.nexus_ver }}
#           ${{ if in(parameters.network,'sgan')}}:
#             vault: $(YMD_ANSIBLE_VAULT_KEY)
#           ${{ if in(parameters.network,'ymd')}}:
#             vault: $(YMD_ANSIBLE_VAULT_KEY)
#       # - template: .deploy.yml
#       #   parameters:
#       #     version: ${{ parameters.nexus_ver }}
#       # - job: NexusHostPost
#       #   displayName: Setup boot persistance for Nexus containers
#       #   dependsOn:
#       #     - NexusDeployment
#       #   condition: succeeded()
#       #   steps:
#       #     - template: .post.yml


