version: "3.3"
services:
  nexus3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.nexus3
      args:
        TAG_VERSION: ${TAG_VERSION}
    cap_add:
      - ALL
    stop_grace_period: 3600s
    container_name: nexus
    hostname: ${HOST_NAME}
    ports:
      - "443:8443"
      - "5443:5443"
      - "5444:5444"
      - "5445:5445"
      - "5446:5446"
      - "5447:5447"
    expose:
      - "8443"
      - "5443"
      - "5444"
      - "5445"
      - "5446"
      - "5447"
    networks:
      nexusnet:
        aliases:
          - nxs
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms4096m -Xmx4096m -XX:MaxDirectMemorySize=4096m -Djava.util.prefs.userRoot=/nexus-data/javaprefs -Djavax.net.ssl.keyStore=/nexus-data/etc/ssl/keystore.pkcs12 -Djavax.net.ssl.keyStorePassword=password"
    volumes:
      - /opt/nexus:/nexus-data:Z
      - /etc/letsencrypt:/etc/letsencrypt:Z
    logging:
      driver: journald
      options:
        tag: nexus
networks:
  nexusnet:
