---
- name: Allow SELinux port access (nexus)
  community.general.seport:
    ports: 443, 5443, 5444, 5445, 5446, 5447
    proto: tcp
    setype: http_port_t
    state: present
- name: Allow SELinux port access (openldap)
  community.general.seport:
    ports: 1389, 1636
    proto: tcp
    setype: http_port_t
    state: present
- name: Set http_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
- name: Add Docker Repo Firewalld service (RHEL)
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/docker-registry-ssl.xml"
    dest: /etc/firewalld/services/docker-registry-ssl.xml
    mode: '0644'
- name: Add Docker Repo Firewalld service (RHEL)
  ansible.builtin.template:
    src: "{{ playbook_dir }}/files/openldap.xml"
    dest: /etc/firewalld/services/openldap.xml
    mode: '0644'
- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
- name: Enable services on the VM Host
  ansible.posix.firewalld:
    service: "{{ srv_name }}"
    permanent: true
    state: enabled
  loop:
    - https
    - docker-registry-ssl
    - openldap
  loop_control:
    loop_var: srv_name
- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
