- name: Adding some folders for binding
  file:
    path: "{{ nxspath }}"
    state: directory
  loop:
    - /opt/nexus
    - /opt/nexus/etc
    - /opt/nexus/etc/ssl
  loop_control:
    loop_var: nxspath
# - name: Adding SSL Application Port
#   ini_file:
#     path: "/opt/nexus/etc/nexus.properties"
#     section:
#     no_extra_spaces: yes
#     option: "{{ ssl_setting['name'] }}"
#     value: "{{ ssl_setting['value'] }}"
#   loop:
#     - name: application-port-ssl
#       value: 8443
#     - name: nexus-args
#       value: "${jetty.etc}/jetty.xml,${jetty.etc}/jetty-https.xml,${jetty.etc}/jetty-requestlog.xml"
#     - name: "ssl.etc"
#       value: "${karaf.data}/etc/ssl"
#   loop_control:
#     loop_var: ssl_setting
# - name: Build Nexus keystore
#   include_tasks: keystore.yml
# - name: Setup the VM options
#   template:
#     src: "{{ playbook_dir }}/templates/nexus.vmoptions.j2"
#     dest: /opt/nexus/nexus.vmoptions
- name: Install certbot
  yum:
    name: certbot
    state: latest