- name: Adding some folders for binding
  file:
    path: "{{ nxspath }}"
    state: directory
  loop:
    - /opt/nexus
    - /opt/nexus/etc
    - /opt/nexus/etc/ssl
  loop_control:
    loop_var: nxspath
# - name: Adding SSL Application Port
#   ini_file:
#     path: "/opt/nexus/etc/nexus.properties"
#     section:
#     no_extra_spaces: yes
#     option: "{{ ssl_setting['name'] }}"
#     value: "{{ ssl_setting['value'] }}"
#   loop:
#     - name: application-port-ssl
#       value: 8443
#     - name: nexus-args
#       value: "${jetty.etc}/jetty.xml,${jetty.etc}/jetty-https.xml,${jetty.etc}/jetty-requestlog.xml"
#     - name: "ssl.etc"
#       value: "${karaf.data}/etc/ssl"
#   loop_control:
#     loop_var: ssl_setting
# - name: Build Nexus keystore
#   include_tasks: keystore.yml
# - name: Setup the VM options
#   template:
#     src: "{{ playbook_dir }}/templates/nexus.vmoptions.j2"
#     dest: /opt/nexus/nexus.vmoptions
- name: Install certbot
  yum:
    name: certbot
    state: latest
- name: Setup/Renew certificate
  command: "certbot certonly --manual --preferred-challenges dns -d {{ certbot[inventory].domain }}"
  ignore_errors: yes
- name: Generate PKCS#12 file
  community.crypto.openssl_pkcs12:
    action: export
    path: "/opt/nexus/etc/ssl/keystore.pkcs12"
    passphrase: password
    friendly_name: nexus
    privatekey_path: "/etc/letsencrypt/live/{{ certbot[inventory].path }}/privkey.pem"
    certificate_path: "/etc/letsencrypt/live/{{ certbot[inventory].path }}/fullchain.pem"
    # other_certificates_parse_all: yes
    # other_certificates: "/opt/nexus/etc/ssl/ca.txt"
    state: present
- name: Import a pkcs12 keystore and create a JKS keystore
  java_cert:
    pkcs12_path: "/opt/nexus/etc/ssl/keystore.pkcs12"
    pkcs12_password: password
    pkcs12_alias: nexus
    cert_alias: nexus
    keystore_path: "/opt/nexus/etc/ssl/keystore.jks"
    keystore_pass: password
    keystore_create: yes
    state: present
