- name: Adding some folders for binding
  file:
    path: "{{ nxspath }}"
    state: directory
    owner: 200
    group: 200
  loop:
    - /opt/nexus
    - /opt/nexus/etc
    - /opt/nexus/etc/ssl
  loop_control:
    loop_var: nxspath
- name: Adding SSL Application Port
  ini_file:
    path: "/opt/nexus/etc/nexus.properties"
    section:
    no_extra_spaces: yes
    option: "{{ ssl_setting['name'] }}"
    value: "{{ ssl_setting['value'] }}"
  loop:
    - name: application-port-ssl
      value: 8443
    - name: nexus-args
      value: "${jetty.etc}/jetty.xml,${jetty.etc}/jetty-https.xml,${jetty.etc}/jetty-requestlog.xml"
    - name: "ssl.etc"
      value: "${karaf.data}/etc/ssl"
  loop_control:
    loop_var: ssl_setting
# - name: Build Nexus keystore
#   include_tasks: keystore.yml
- name: Setup the VM options
  template:
    src: "{{ playbook_dir }}/templates/nexus.vmoptions.j2"
    dest: /opt/nexus/nexus.vmoptions
- name: Install certbot
  yum:
    name: certbot
    state: latest
# - name: Setup/Renew certificate
#   command: "certbot certonly --manual --email {{ certbot[inventory].email }} --preferred-challenges dns --agree-tos -d {{ certbot[inventory].domain }}"
#   ignore_errors: yes
- name: Install openssl and OpenJDK 11
  yum:
    name: 
      - openssl
      - java-11-openjdk-headless
    state: latest
- name: Create the sysconfig file
  copy:
    content: |
      KEYSTORE_PATH=/opt/nexus/etc/ssl/keystore.jks
      CERTBOT_DOMAIN={{ certbot[inventory].path }}
    dest: /etc/sysconfig/nexus
- name: Add cron script
  copy: 
    src: "{{ playbook_dir }}/files/updatecert"
    dest: /etc/cron.daily/updatecert
    mode: 0755
- name: Run the updatecert
  command: /etc/cron.daily/updatecert
- name: Set the permissions on the JKS
  file:
    path: /opt/nexus/etc/ssl/keystore.jks
    owner: 200
    group: 200
# - name: Gather the LetEncrypt certs into a single file  
#   shell: |
#     cat /etc/letsencrypt/live/{{ certbot[inventory].path }}/*.pem > ./keystore.pem
#     openssl pkcs12 -export -out /./keystore.pkcs12 -in ./keystore.pem -passout pass:password -name nexus
#     rm -f ./keystore.jks
#     keytool -v -importkeystore -srckeystore keystore.pkcs12 -destkeystore keystore.jks -deststoretype JKS -deststorepass password -srcstorepass password
#     rm -f ./keystore.pkcs12; rm -f ./keystore.pem
#   args:
#     chdir: /opt/nexus/etc/ssl/
# - name: Generate PKCS#12 file
#   community.crypto.openssl_pkcs12:
#     action: export
#     path: "/opt/nexus/etc/ssl/keystore.pkcs12"
#     passphrase: password
#     friendly_name: nexus
#     privatekey_path: "/etc/letsencrypt/live/{{ certbot[inventory].path }}/privkey.pem"
#     certificate_path: "/etc/letsencrypt/live/{{ certbot[inventory].path }}/fullchain.pem"
#     # other_certificates_parse_all: yes
#     # other_certificates: "/opt/nexus/etc/ssl/ca.txt"
#     state: present
# - name: Import a pkcs12 keystore and create a JKS keystore
#   java_cert:
#     pkcs12_path: "/opt/nexus/etc/ssl/keystore.pkcs12"
#     pkcs12_password: password
#     pkcs12_alias: nexus
#     cert_alias: nexus
#     keystore_path: "/opt/nexus/etc/ssl/keystore.jks"
#     keystore_pass: password
#     keystore_create: yes
#     state: present
