---
- name: Prepare the host for Nexus
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Setup firewall
      include_tasks: firewall.yml
    - name: Setup Nexus config
      include_tasks: nexus-config.yml
    - name: Enable systemd service
      systemd:
        name: container-nexus
        state: stopped
      ignore_errors: true
