name: Deploy Nexus
on:
  workflow_dispatch:
    inputs:
      deploy-tag:
        required: true
        type: string
        description: Enter the Nexus tag for deployment
        default: latest
      environment:
        type: environment
        description: Select the environment
      deploy-inventory:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - home
      deploy-group:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - nexus
      # build_id:
      #   required: true
      #   type: number
      # deploy_target:
      #   required: true
      #   type: string
      # perform_deploy:
      #   required: true
      #   type: boolean

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
  CONFIG_MAP: |
    home:
      vault: HOME_ANSIBLE_VAULT_KEY
      private: HOME_SSH_PRIVATE_KEY
      group: nexus
      user: jam
      network: sgan

jobs:
  prepare:
    name: Prepare the host for Nexus
    runs-on: [ self-hosted, medium, build ]
    # container:
    #   image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
    #   options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
    #   credentials:
    #     username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
    #     password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    outputs:
      ansible_config: ${{ steps.set-ansible-config.outputs.ansible_config }}
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Get Ansible Config
        id: set-ansible-config
        run: |
          echo "ansible_config=$(echo -n '${{ env.CONFIG_MAP}}' | yq -r -o=json - | jq '.${{ github.event.inputs.environment }}' -c)" >> $GITHUB_OUTPUT
      # - name: Add the key
      #   uses: JamesJonesConsulting/github.ssh-add-b64.action@main
      #   with:
      #     encoded-key: ${{ secrets[fromJson(steps.set-ansible-config.outputs.ansible_config).private] }}
      - name: Connect to Nexus hosts and setup pre-requirements
        run: |
          eval $(ssh-agent); ssh-add <(echo -n '${{ secrets[fromJson(steps.set-ansible-config.outputs.ansible_config).private] }}' | base64 -d);
          git clone -b ${{ env.ANSIBLE_INVENTORY_REPO_BRANCH }} --single-branch ${{ env.ANSIBLE_INVENTORY_REPO }} ansible/inventory
          git clone -b ${{ env.ANSIBLE_VAULT_REPO_BRANCH }} --single-branch ${{ env.ANSIBLE_VAULT_REPO }} ansible/vault
          # ansible-galaxy role install -r ansible/requirements.yml -p ansible/roles -f
          ansible-galaxy collection install -r ansible/requirements.yml -f
          echo "${{ secrets[fromJson(steps.set-ansible-config.outputs.ansible_config).vault] }}" > ${RUNNER_TEMP}/.keyvault
          ansible-playbook --vault-password-file=${RUNNER_TEMP}/.keyvault -i ansible/inventory/${{ github.event.inputs.environment }}/hosts -u ${{ fromJson(steps.set-ansible-config.outputs.ansible_config).user }} ansible/playbook.yml -e 'inventory_group_name=${{ fromJson(steps.set-ansible-config.outputs.ansible_config).group }} inventory=${{ github.event.inputs.environment }} certpath=${{ fromJson(steps.set-ansible-config.outputs.ansible_config).group }}' -vvv
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_TIMEOUT: 120
          # LETSENCRYPT_HOST_CERT_PATH: /etc/letsencrypt/live/{{ parameters.networks[parameters.network].letsencrypt_host }}
          # TAG_VERSION: {{ parameters.version.nexus3 }}
          # OPENLDAP_TAG_VERSION: {{ parameters.version.openldap }}
          # HOST_NAME: {{ parameters.networks[parameters.network]['hostname'] }}
          # LETSENCRYPT_HOST: {{ parameters.networks[parameters.network].letsencrypt_host }}
          # LDAP_ROOT: {{ parameters.networks[parameters.ldap]['root'] }}
          # LDAP_USER: {{ parameters.networks[parameters.ldap]['user'] }}
          # LDAP_PASSWORD: {{ parameters.networks[parameters.ldap]['password'] }}
          # LDAP_ADMIN_USER: {{ parameters.networks[parameters.ldap]['admin']['user'] }}
          # LDAP_ADMIN_PASSWORD: {{ parameters.networks[parameters.ldap]['admin']['password'] }}
