name: Deploy Nexus
on:
  workflow_dispatch:
    inputs:
      deploy-tag:
        required: true
        type: string
        description: Enter the Nexus tag for deployment
        default: latest
      agent-label:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - artifactory
      # build_id:
      #   required: true
      #   type: number
      # deploy_target:
      #   required: true
      #   type: string
      # perform_deploy:
      #   required: true
      #   type: boolean

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}

jobs:
  prepare:
    name: Prepare the host for Nexus
    runs-on: [ self-hosted, '${{ inputs.agent-label }}' ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.NEXUS_REGISTRY }}
          username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
          password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
