name: Deploy Nexus
on:
  workflow_dispatch:
    inputs:
      deploy-tag:
        required: true
        type: string
        description: Enter the Nexus tag for deployment
        default: latest
      deploy-inventory:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - home
      deploy-group:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - nexus
      # build_id:
      #   required: true
      #   type: number
      # deploy_target:
      #   required: true
      #   type: string
      # perform_deploy:
      #   required: true
      #   type: boolean

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}

jobs:
  prepare:
    name: Prepare the host for Nexus
    runs-on: [ self-hosted, medium, build ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Add the key
        uses: JamesJonesConsulting/github.ssh-add-b64.action@main
        with:
          encoded-key: ${{ secrets.HOME_SSH_PRIVATE_KEY }}

      
      # - name: Check matrix definition
      #   run: |
      #     matrix='${{ needs.matrix.outputs.matrix }}'
      #     echo $matrix
