name: Deploy Nexus
on:
  workflow_dispatch:
    inputs:
      deploy-tag:
        required: true
        type: string
        description: Enter the Nexus tag for deployment
        default: latest
      deploy-inventory:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - home
      deploy-group:
        required: true
        type: choice
        description: Enter the Nexus tag for deployment
        options: 
          - nexus
      # build_id:
      #   required: true
      #   type: number
      # deploy_target:
      #   required: true
      #   type: string
      # perform_deploy:
      #   required: true
      #   type: boolean

env:
  NEXUS_DOCKER_USER: ${{ secrets.HOME_NEXUS_DOCKER_USER }}

jobs:
  prepare:
    name: Prepare the host for Nexus
    runs-on: [ self-hosted, medium, build ]
    container:
      image: nexus.jamesjonesconsulting.com:5443/jamesjonesconsulting/podman-dind-like:latest
      options: --userns=keep-id --group-add keep-groups --privileged --user root --security-opt seccomp=unconfined
      credentials:
        username: ${{ secrets.HOME_NEXUS_DOCKER_USER }}
        password: ${{ secrets.HOME_NEXUS_DOCKER_PASSWORD }}
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Add the key
        uses: JamesJonesConsulting/github.ssh-add-b64.action@main
        with:
          encoded-key: ${{ secrets.HOME_SSH_PRIVATE_KEY }}
      - name: Connect to Nexus hosts and setup pre-requirements
        run: |
          ansible-galaxy role install -r ansible/requirements.yml -p ansible/roles
          ansible-galaxy collection install -r ansible/requirements.yml
          # ansible-playbook --vault-password-file=$(Agent.TempDirectory)/.keyvault --key-file=$(hostKey.secureFilePath) -i ansible/roles/inventory/${{ parameters.network }} -u ${{ parameters.networks[parameters.network].host_user }} ansible/playbook-pre.yml -e 'inventory_group_name=${{ parameters.networks[parameters.network].group }} inventory=${{ parameters.network }} certpath=${{ parameters.networks[parameters.network].certpath }}' -vvv
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_TIMEOUT: 120
          # LETSENCRYPT_HOST: /etc/letsencrypt/live/${{ parameters.networks[parameters.network].letsencrypt_host }}

